services:
  app-demo:
    build: ./demo
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web

  app-main:
    build: ./client
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - web

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web
    depends_on:
      app-demo:
        condition: service_started
        required: false
      app-main:
        condition: service_started
        required: false

networks:
  web:

volumes:
  caddy_data:
  caddy_config:
